head: "一些不错的中文播客 :smile:
- **Podcasts软件**: [Android](#android_app) / [IOS](#ios_app) / [MacOS](#macos_app) / [Linux](#linux_app) / [web](#web_app)
- [**英语podcasts**](https://github.com/rShetty/awesome-podcasts)"
foot: "## 博客软件
###

"

icons:
  rss: https://upload.wikimedia.org/wikipedia/commons/d/d9/Rss-feed.svg
  twitter: https://upload.wikimedia.org/wikipedia/commons/8/8b/Twitter_logo_initial.svg
  liscense: https://upload.wikimedia.org/wikipedia/commons/6/62/PD-icon.svg